config/routes.rb
Rails.application.routes.draw do

  root 'case_sets#index'
  resources :case_sets do
    resources :cases do
      resources :tasks
    end
  end
  match 'auth/:provider/callback', to: 'sessions#create', as: 'signin', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/case.rb
class Case < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :case_num, :presence => true
  accepts_nested_attributes_for :tasks, allow_destroy: true

  def self.get_salesforce_cases(user)
    @client = Restforce.new :oauth_token => user.oauth_token,
     :refresh_token => user.refresh_token,
     :instance_url  => user.instance_url,
     :client_id     => ENV['SALESFORCE_KEY'],
     :client_secret => ENV['SALESFORCE_SECRET'] 

    raw_cases = @client.query("SELECT Id, CaseNumber, Subject, Owner.Name, Owner.Email,
     (SELECT Next_Action__c,Action_Due_Date__c,Action_Owner__c 
     FROM Support_Action_Plans__r) FROM Case 
     WHERE ((Escalation_Type__c='Tier 1 - Escalation') 
     AND (Status NOT IN ('7 - Close Pending Customer','8 - Closed')))")
    build_case_set_hash(raw_cases)
  end

  def self.push_to_tp3(case_set)
    # figure out what doesn't have a tp3_id or has changed
    case_set.cases.each do |case_obj|
      if case_obj.tp3_id.nil?
        project_response = HTTParty.post(ENV['TARGETPROCESS_URL']+'Projects', :headers => { 'Content-Type' => 'application/json' }, :body => { 'Name' => "#{case_obj.case_num}" }.to_json, :query => {format: "json", token: ENV['TARGETPROCESS_API_KEY']})
        # should check if the post fails
        case_obj.update(tp3_id: "#{project_response.parsed_response["Id"]}")
        if case_obj.tasks
          case_obj.tasks.each do |task_obj|
            task_response = HTTParty.post(ENV['TARGETPROCESS_URL']+'UserStories', :headers => { 'Content-Type' => 'application/json' }, :body => { 'Name' => "#{task_obj.next_action}", "Project"=>{"Id"=>"#{case_obj.tp3_id}"} }.to_json, :query => {format: "json", token: ENV['TARGETPROCESS_API_KEY']})
            task_obj.update(tp3_id: "#{task_response.parsed_response["Id"]}")
          end
        end
      end
    end
    # push to tp3
    # get the tp3_id if needed
    # else display success via flash notice
  end

  def self.build_case_set_hash(case_collection)
    #return_hash = Hash.new
    escalation_engineers = get_current_esc_engineers
    return_string = "{:case_set=>"
    return_string += "{:cases_attributes=>["
    case_collection.each do |case_obj| 
      if escalation_engineers.include?("#{case_obj.Owner.Email}")
        return_string += "{:case_num=>\"#{case_obj.CaseNumber}\"," +
                         ":url=>\"https://meraki.my.salesforce.com/#{case_obj.Id}\"," +
                         ":description=>\"#{case_obj.Subject.gsub(/[^0-9A-Za-z ]/, '')}\"," +
                         ":owner=>\"#{case_obj.Owner.Name}\""
                         # tasks_attributes addition in the hash are here
                         if case_obj.Support_Action_Plans__r
                           return_string += ",:tasks_attributes=>["
                             case_obj.Support_Action_Plans__r.each do |task_obj|
                               return_string += "{:owner=>\"#{task_obj.Action_Owner__c}\"," +
                                                ":due_date=>\"#{task_obj.Action_Due_Date__c}\"," +
                                                ":next_action=>\"#{task_obj.Next_Action__c}\","
                             end
                           return_string += "},]"
                         end
        return_string += "},"
      end
    end
    return_string += "]}}"
    Rails.logger.debug "#{return_string}"
    eval(return_string)
  end

  def self.get_current_esc_engineers
    esc_array = []
    results = @client.query("SELECT Id, Email FROM User WHERE UserRole.Name='Escalation Engineer'")
    results.each do |engineer_email|
      esc_array.push(engineer_email.Email)
    end
    esc_array
  end
end

app/models/case_set.rb
class CaseSet < ActiveRecord::Base
  has_many :cases, dependent: :destroy
  accepts_nested_attributes_for :cases, allow_destroy: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :case
  validates :owner, :next_action, :due_date, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
#    puts auth
#    binding.pry # view what's in the returned omniauth hash from Salesforce
    where(auth.slice(:provider, :uid).permit!).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.refresh_token = auth.credentials.refresh_token
      user.instance_url = auth.credentials.instance_url
      user.save!
    end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/case_sets_controller.rb
class CaseSetsController < ApplicationController

  def index
    @case_sets = CaseSet.all.reverse
  end

  def show
    @cases = Case.where(:case_set_id=> params[:id])
  end

  def new
    @cases = Case.get_salesforce_cases(current_user)
  end

  def create
    @case_set = CaseSet.create(case_set_params)
    Case.push_to_tp3(@case_set)
    flash[:success] = "Case set ##{@case_set.id} created successfully!"
    redirect_to root_path
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_set_params
      #params.require("case_set").permit("cases_attributes": ["case_num","description","owner","url"])
      params.require(:case_set).permit(cases_attributes: [:case_num,:description,:owner,:url,:tasks_attributes => [:owner,:due_date,:next_action]])
    end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @case_set = Case.group(:case_set_id).count
  end

  def show
    @case = Case.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    if user
      log_in(user)
      redirect_to case_sets_path
    else
      flash.now[:danger] = 'Unable to contact Salesforce'
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.where(:case_id => params[:case_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_helper.rb
module CaseHelper
end

app/helpers/case_sets_helper.rb
module CaseSetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/case_sets/index.html.erb
<div class="list-inline" >
  <%= link_to 'View on TP3', ENV['TARGETPROCESS_URL'], class: 'btn btn-info btn-xs pull-right', :target => '_blank' %>
  <%= link_to 'New Case Set', new_case_set_path, class: 'btn btn-primary btn-xs pull-right', style: 'margin-right: 5px' %>
  <h3>Case Sets</h3>
</div>
<div class="row">
  <table class="table">
    <tr>
      <th>Case_Set #</th>
      <th>Date Generated</th>
      <th># of Cases</th>
    </tr>
    <% @case_sets.each do |case_set| %>
      <tr> 
        <th><%= case_set.id %></th>
        <th><%= case_set.created_at %></th>
        <th><%= link_to case_set.cases.size, case_set_path(case_set.id) %></th>
      </tr>
    <% end %>
 </table>
</div>

app/views/case_sets/new.html.erb
<div class="list-inline" >
  <%= link_to 'Cancel', root_path, class: 'btn btn-warning btn-xs pull-right' %>
  <%= button_to 'Push to TP3', case_sets_path(@cases), :method => :post, class: 'btn btn-success btn-xs pull-right', style: 'margin-right: 5px' %>
  <h3>Escalation's Current Cases</h3>
</div>
<div class="row">
  <table class="table">
    <tr>
      <th>Case #</th>
      <th>Description</th>
      <th>Owner</th>
    </tr>
    <% @cases[:case_set][:cases_attributes].each do |case_obj| %>
      <tr>
        <th><%= link_to case_obj[:case_num], case_obj[:url]  %></th>
        <th><%= case_obj[:description] %></th>
        <th><%= case_obj[:owner] %></th>
      </tr>
    <% end %>
 </table>
</div>

app/views/case_sets/show.html.erb
<div class="list-inline" >
  <h3>Case Set # <%= @cases.first.case_set_id %></h3>
</div>
<div class="row">
  <table class="table">
    <tr>
      <th>Case #</th>
      <th>Description</th>
      <th>Owner</th>
      <th># of Tasks</th>
    </tr>
    <% @cases.each do |case_obj| %>
      <tr>
        <th><%= link_to case_obj.case_num, case_obj.url %></th>
        <th><%= case_obj.description %></th>
        <th><%= case_obj.owner %></th>
        <th><%= link_to case_obj.tasks.size, case_set_case_path(:case_set_id => case_obj.case_set_id, :id => case_obj.id) %></th>
      </tr>
    <% end %>
 </table>
</div>

app/views/cases/index.html.erb
<div class="row">
  <table class="table">
    <tr>
      <th>Case #</th>
      <th>Description</th>
      <th>Owner</th>
      <th># of Tasks</th>
    </tr>
    <% @cases.each do |case_obj| %>
      <tr>
        <th><%= link_to case_obj.case_num, case_obj.url %></th>
        <th><%= case_obj.description %></th>
        <th><%= case_obj.owner %></th>
        <th><%= link_to case_obj.tasks.size, case_set_case_tasks_path(:case_id => case_obj.id) %></th>
      </tr>
    <% end %>
 </table>
</div>

app/views/cases/show.html.erb
<div class="list-inline" >
  <h3>Case # <%= @case.case_num %></h3>
</div>
<div class="row">
  <table class="table">
    <tr>
      <th>Task #</th>
      <th>Next Action</th>
      <th>Owner</th>
      <th>Due Date</th>
    </tr>
    <% @case.tasks.each_with_index do |task_obj, index| %>
      <tr>
        <th><%= link_to index+1, @case.url %></th>
        <th><%= task_obj.next_action %></th>
        <th><%= task_obj.owner %></th>
        <th><%= task_obj.due_date %></th>
      </tr>
    <% end %>
 </table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Escalations Task App", root_path, :class => "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to "Log out", signout_path %>
        </li>
      <% else %>
        <li><%= link_to "Log in", '/auth/salesforce' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Tp3</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %> 

    <div class="container">
      <div class="row">
        <% if logged_in? %>
          <%= yield %>
        <% end %>
      </div>
    </div>

  </body>
</html>
<%= debug(params) if Rails.env.development? %>

app/views/tasks/index.html.erb
<div class="row">
  <table class="table">
    <tr>
      <th>Task #</th>
      <th>Next Action</th>
      <th>Owner</th>
      <th>Due Date</th>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <th><%= task.id %></th>
        <th><%= task.next_action %></th>
        <th><%= task.owner %></th>
        <th><%= task.due_date %></th>
      </tr>
    <% end %>
 </table>
</div>